# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('rented', models.BooleanField(default=False)),
                ('last_rented', models.DateTimeField()),
            ],
        ),
    ]
