# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20170618_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
