# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_auto_20170618_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='last_rented',
        ),
    ]
