# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_remove_license_last_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='rented',
        ),
        migrations.AddField(
            model_name='license',
            name='rent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
