# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_auto_20170619_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
