# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0007_license_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='rented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL),
        ),
    ]
