# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_license_rented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='rented_by',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
