# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_auto_20170619_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='rented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL),
        ),
    ]
